MODULE INPUT

integer,parameter :: XP =  selected_real_kind(15)

REAL(KIND=XP),PARAMETER :: M = 200.0_XP
REAL(KIND=XP),PARAMETER :: M_0_DOT = 10000.0_XP
REAL(KIND=XP),PARAMETER :: R_MAX_DECLARED = 100.0_XP
REAL(KIND=XP),PARAMETER :: ALPHA = 1E6_XP
REAL(KIND=XP),PARAMETER :: X=0.7_XP
REAL(KIND=XP),PARAMETER :: Y=0.2_XP
REAL(KIND=XP),PARAMETER :: Z=1.0_XP-X-Y

END MODULE INPUT 
