MODULE INPUT

REAL(KIND=XP),PARAMETER :: M = 1_XP
REAL(KIND=XP),PARAMETER :: M_0_DOT = 1_XP
REAL(KIND=XP),PARAMETER :: R_MAX = 90.0_XP
REAL(KIND=XP),PARAMETER :: ALPHA = 1_XP
REAL(KIND=XP),PARAMETER :: X=1_XP
REAL(KIND=XP),PARAMETER :: Y=1_XP

PRINT*, '----------INITIALISATION---------'
PRINT*, '---VALEURS PARAMETRES EN INPUT---'
PRINT*,'MASSE DU TROU NOIR = ',M

END MODULE INPUT 
